Адаптивные сетки
PolinaGoltsova/2368577-cat-energy-2 pull request #10
Opened 2024-10-22 13:00 UTC by PolinaGoltsova

Максим, привет!
У меня несколько вопросов:
1. я задала ширину экранов и маргины, чтобы контент не прилипал, но контент все равно не встает по центру. 
2. как в background-image добавить изображение в 1х и 2х? тоже создавать медиазапросы для экранов с разной протностью?
3. почему font-weight в заголовках Н2 отображается bold, хотя в стилях указан 400? 
4. крупные цифры в блоке "Как это работает" в index я добавила в разметку. Или их нужно добавлять фоном?

2024-10-24 07:41 UTC, brewscriptor commented on source/styles/blocks/page.scss
> +    margin: 0 110px;
1. Попробуй делать не фиксированный отступ справа/слева, а адаптивный.
Возможно, `margin: 0 auto` тут может сработать
```suggestion
    margin: 0 auto;
```

2024-10-24 07:41 UTC, brewscriptor commented on source/styles/blocks/page.scss
> +  margin: 0 20px;
```suggestion
  margin: 0 auto;
```

2024-10-24 07:41 UTC, brewscriptor commented on source/styles/blocks/page.scss
> +    margin: 0 30px;
```suggestion
    margin: 0 auto;
```

2024-10-24 07:41 UTC, brewscriptor commented on source/styles/blocks/page.scss
> +    margin: 0 110px;
🟢 существуют разные способы выставить контент по центру.
Это, пожалуй, самый популярный вопрос на собесах: "Как отцентровать div" 😄 Желательно знать от 3х и более способов.
Вот [тут](https://tproger.ru/articles/kak-centrirovat-chto-ugodno-v-css?ysclid=m2myfsce1k48580090) очень хорошо описана проблема.
Как правило, в жизни используют центрирование автоматическим марджином (как я предложил) или флексом.

2024-10-24 07:41 UTC, brewscriptor commented on source/styles/blocks/main-description.scss
> +    background-image: url("../../images/background-main-image-mobile@2x.png");
2. Да, используя медиа запросы нужно добавлять ретинизацию.
Вот хорошая [статья](https://htmlacademy.ru/blog/html/retina?ysclid=m2mynbsnmu511243953) о том, как это делается с примерами.
Нам можно делать без префиксов `webkit`

2024-10-24 07:41 UTC, brewscriptor commented on source/styles/blocks/main-description.scss
>  .main-description__title {
3. Тут тебе нужно явно указать, что заголовок должен иметь `font-weight: 400;`
либо указать, что это свойство должно наследоваться от родителя `font-weight: inherit;`
Первый вариант лучше.
В противном случае браузер видит, что это h2 заголовок и ставит дефолтные стили для заголовка font-weight: bold;
<img width="1704" alt="Screenshot 2024-10-24 at 10 33 42" src="https://github.com/user-attachments/assets/eeadb6d4-7679-4935-8cb3-a584ea0e2494">

2024-10-24 07:41 UTC, brewscriptor commented on source/index.html
> +          <span class="benefits__item-number">1</span>
4. Да, такой вариант подходит.
Есть продвинутый подход - добавить счётчик в CSS. Тогда эти цифры станут псевдоэлементами. Из плюсов - нет лишней вёрстки, счётчик автоматический и если дизайнер попросит добавить новый пункт - он автоматически получит цифру 5, не нужно будет менять вёрстку.
Более подробно про это [тут](https://doka.guide/css/css-counters/?ysclid=m2mztahc96245888341).

2024-10-24 15:01 UTC, PolinaGoltsova commented on source/index.html
> +          <span class="benefits__item-number">1</span>
![image](https://github.com/user-attachments/assets/459d2046-0941-48e9-a4b0-30bd66d5350d)
@brewscriptor понравилась идея со счетчиком, получилось его добавить, но не пойму, как стилизовать. Почему-то свойстро font-weight не срабатывает

2024-10-24 15:35 UTC, PolinaGoltsova commented on source/styles/blocks/main-description.scss
> +    background-image: url("../../images/background-main-image-decktop@1x.png");
@brewscriptor Максим, добавила тут изображение в ретине, но оно не отрабатывает. Показывает только в 1х. Это из-за того, что тут псевдоэлемент?

2024-10-24 15:41 UTC, PolinaGoltsova commented on source/styles/blocks/page.scss
> +    margin: 0 110px;
@brewscriptor добавила на .page__body маргин 0 авто и паддинг 0 20px (чтобы были уши и контент не прилипал). Но теперь не могу понять, как мне растянуть фоновые изображения и карту по ширине всего экрана (без учета паддингов)? 
![image](https://github.com/user-attachments/assets/81d593e6-e821-449d-883a-f1de57d9b3a7)

2024-10-26 05:13 UTC, brewscriptor commented on source/styles/blocks/page.scss
> +    margin: 0 110px;
возможно, нужно ещё раз попробовать подумать и прикинуть как разный контент будет располагаться на странице. можно представить body как просто контейнер без отступов, тогда у нас будет три раздела: хэдер, мэйн и футер. каждый из этих разделов имеет своё поведение. можно попробовать задавать им отступ от боди, а у боди убрать. это как раз категория задачи на архитектуру сетки страницы, это нормально что в процессе работы она будет меняться и не раз.

2024-10-26 05:14 UTC, brewscriptor commented on source/styles/blocks/page.scss
> +    margin: 0 110px;
вообще, я не сторонник стилизовать тэги html и body

2024-10-26 05:30 UTC, brewscriptor commented on source/index.html
> +          <span class="benefits__item-number">1</span>
для селектора `.benefits__item::before` не верно задано значение свойства content.
нужно это исправить и потом всё применится 👍🏻

2024-10-26 05:31 UTC, brewscriptor commented on source/styles/blocks/main-description.scss
> +    background-image: url("../../images/background-main-image-decktop@1x.png");
ответил в телеграм

2024-10-27 06:36 UTC, brewscriptor requested changes

2024-10-27 06:36 UTC, brewscriptor commented on source/catalog.html
> +          <a class="navigation__link navigation__link--dark" href="index.html">ГЛАВНАЯ</a>
🔴 апперкейс надо делать только стилями, а не регистром

2024-10-27 06:36 UTC, brewscriptor commented on source/index.html
> +          <a class="navigation__link" href="catalog.html">КАТАЛОГ ПРОДУКЦИИ</a>
🔴 апперкейс через стили нужен

2024-10-27 06:36 UTC, brewscriptor commented on source/index.html
> +          <!-- <span class="benefits__item-number">1</span> -->
🟢 комменты можно удалить

2024-10-27 06:36 UTC, brewscriptor commented on source/styles/blocks/additional-products.scss
>  // .additional-products__value {
🟢 рекомендую не хранить классы в html и css как заготовки, а добавлять тогда, когда появляется в этом необходимость

2024-10-27 06:36 UTC, brewscriptor commented on source/styles/blocks/benefits.scss
>  .benefits__item::before {
🔴 вот тут надо изменить значение у `content`
или попробовать создать ::after и вынести всё, что касается счётчика туда

2024-10-27 06:36 UTC, brewscriptor commented on source/styles/blocks/benefits.scss
>  .benefits__item::before {
ага, вот доскроллил и увидел, что ::after тоже используется.
тогда предлагаю подумать как можно что-то объединить и вынести в одно правило.

2024-10-27 06:36 UTC, brewscriptor commented on source/styles/common/global.scss
> +  font-weight: 400;
🔴 лучше не задавать стили глобально по тэгу. бывает, когда дефолтное поведение ожидается другими разработчиками/в других местах приложения.
если нужно переопределить дефолтное поведение заголовка h2 - лучше это делать в том месте (классе), где это нужно.
если таких мест много - обрати внимание на [миксины](https://sass-scss.ru/documentation/miksini/ispolzovanie_miksina/).

2024-10-29 06:53 UTC, merged