Добавляет адаптивные декоративные элементы
PolinaGoltsova/2368577-cat-energy-2 pull request #11
Opened 2024-11-02 17:27 UTC by PolinaGoltsova

Максим, привет! 
Направляю на проверку index.html
У меня есть некоторые сложности:
1. не получается добавить свойство background-color под background-image, фон отображается под всем блоком, а не только под картинкой
2. не получается растянуть фоны на всю ширину экрана
3. не получается добавить hover с изменением цвета на логотип академии в футере

2024-11-03 07:39 UTC, brewscriptor commented
1. Отписался в телеграмм.
2. Чтобы фоны блоков тянулись на всю ширину, нужно чтобы сами эти блоки тянулись. попробую создать демку, где будет такое реализовано.
https://codepen.io/mouxez/pen/yLmEdda

2024-11-03 07:40 UTC, brewscriptor commented on source/index.html
> +        <img class="logo__name-footer" src="images/logo-name.svg" width="128" height="24" alt="название логотипа Кэт энерджи">
3. В зависимости от того, каким именно способом ты вставляешь иконку, зависит будет ли у тебя контроль над ней или нет. В данном случае контроль не полный и цвет заливки менять не получится. Посмотри, у тебя в проекте уже есть места с полным контролем над иконкой.
Вот [тут](https://habr.com/ru/companies/htmlacademy/articles/337284/) можно почитать подробнее.

2024-11-05 16:59 UTC, PolinaGoltsova commented
@brewscriptor Максим, запушила новый коммит, где исправляла размеры блоков и тянущиеся фоны.

2024-11-06 06:44 UTC, brewscriptor requested changes

2024-11-06 06:44 UTC, brewscriptor commented on source/catalog.html
> +      <p class="cooperation__title">Приглашаем <br> к сотрудничеству дилеров!</p>
🔴 для реализации переноса текста лучше использовать ширину блока.
br плох по некоторым причинам
- он добавляет лишнюю html разметку
- иногда при некоторых ширинах вьюпорта br создают жесткие разрывы, которые плохо адаптируются к различным размерам экрана или макетам.
- ухудшает семантику и читабельность

2024-11-06 06:44 UTC, brewscriptor commented on source/catalog.html
> -      <picture>
🔴 вполне возможно, что при определённых условиях скрипт карты может не отработать и пользователь ничего не увидит. будет круто отставить карту в виде картинки как нижний слой, на случай не доступности интерактивной карты.

2024-11-06 06:44 UTC, brewscriptor commented on source/index.html
> +        <h2 class="main-description__title">Функциональное <br> питание для котов</h2>
🔴 br нужно заменить на регулирование переноса через css

2024-11-06 06:44 UTC, brewscriptor commented on source/index.html
> +      <div class="results__container">
🟢 можно вынести css свойства, относящиеся к созданию контейнера в микс класс .container
например, отвечающие за создание необходимой ширины + отступы + медиазапросы для перехода между ширинами

2024-11-06 06:44 UTC, brewscriptor commented on source/index.html
> +      <div class="results__container">
у нас есть определённый паттерн - мобильная версия 320px и центрирование и тд по остальным ширинам

2024-11-06 06:44 UTC, brewscriptor commented on source/index.html
> +      <p class="cooperation__title">Приглашаем <br> к сотрудничеству дилеров!</p>
🔴 br

2024-11-06 06:44 UTC, brewscriptor commented on source/index.html
> -      <picture>
🔴 карту стоит вернуть

2024-11-06 06:44 UTC, brewscriptor commented on source/index.html
> +        <img class="logo__name-footer" src="images/logo-name.svg" width="128" height="24" alt="название логотипа Кэт энерджи">
@PolinaGoltsova у тебя получилось разобраться с иконкой?
чтобы управлять ей, нужно либо в разметку заинлайнить, либо через спрайт

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/benefits.scss
> +  margin: 0 auto;
🟡  можно вынести 
```
width: $mobile-width;
margin: 0 auto;
```
в отдельный микс класс .container и использовать его везде, где есть необходимость центровать контент и выставлять ширину по макету.
Соответственно в этом микс классе будут медиазапросы для других ширин + возможно внутренние отступы, если получается их объединить.

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/button.scss
> +    color: rgb(255, 255, 255, 0.3);
🟢 как правило, на проекте договариваются к одному типу указания цветов (hex, rgb и тд)
в данном случае можно использовать hex и отдельно указать прозрачность

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/cooperation.scss
> +  margin: 0 auto;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/cooperation.scss
> +    width: $tablet-width;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/cooperation.scss
> +  margin: 0 auto;
показываю, какие свойства могут уйти в микс класс.
если все свойства совпадают, то можно использовать на блоках, которые требуют центрирование и автоотступы

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/footer.scss
> +  width: $mobile-width;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/footer.scss
> +    width: $tablet-width;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/footer.scss
> +    width: $desktop-width;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/map.scss
> +.map iframe {
🔴 вижу, что класс .map напрямую не используется нигде.
возможно стоит его перенести на сам iframe с картой и избавиться от `.map iframe`

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/results.scss
> +    height: 0.1px;
🔴 нам точно не нужно указывать дроби тут. нужно всё округлять по правилам математики и указывать только целые числа.

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/results.scss
> +  margin: 0 auto;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/results.scss
> +    width: $tablet-width;
🟡 .container

2024-11-06 06:44 UTC, brewscriptor commented on source/styles/blocks/results.scss
> +    width: $desktop-width;
🟡 .container

2024-11-06 12:36 UTC, PolinaGoltsova commented on source/catalog.html
> +      <p class="cooperation__title">Приглашаем <br> к сотрудничеству дилеров!</p>
сделала с помощью &nbsp;

2024-11-06 14:57 UTC, PolinaGoltsova commented
@brewscriptor Максим, внесла правки по комментариям

2024-11-06 15:36 UTC, brewscriptor approved these changes

2024-11-08 14:29 UTC, PolinaGoltsova commented
@brewscriptor Максим, привет! доделала каталог. Посмотри, пожалуйста, все ли ок

2024-11-09 06:00 UTC, brewscriptor commented
> @brewscriptor Максим, привет! доделала каталог. Посмотри, пожалуйста, все ли ок

всё ок, двигаемся дальше 👍🏻

2024-11-09 06:00 UTC, brewscriptor approved these changes

2024-11-11 08:05 UTC, merged