Добавляет разметку главной страницы и каталога
PolinaGoltsova/2368577-cat-energy-2 pull request #6
Opened 2024-09-22 14:00 UTC by PolinaGoltsova

2024-09-24 04:40 UTC, kjdhaljkd requested changes
Хорошая работа!

2024-09-24 04:40 UTC, kjdhaljkd commented on source/catalog.html
> +    <a class="header_logo logo" href="index.html">
🔴  мы используем синтаксис с двойным подчёркиванием [Two Dashes]( https://up.htmlacademy.ru/adaptive-individual/2/module/2/item/5 ) нотацию. нужно во всех местах и на всех страницах исправить одинарное подчёркивание на двойное.
header_logo => header__logo

2024-09-24 04:40 UTC, kjdhaljkd commented on source/catalog.html
> +            <span class="prproduct-card_measure">Масса</span>
🔴 тоже нужно поправить везде:
опечатка в product
prproduct-card_measure => product-card_measure

2024-09-24 04:40 UTC, kjdhaljkd commented on source/catalog.html
> +    <nav class="header_navigation navigation">
🟢  это минорное, можно не править: как правило, название микс класса указывают первым, для улучшения читабельности кода.

2024-09-24 04:40 UTC, kjdhaljkd commented on source/index.html
> +    <nav class="header_navigation navigation">
🟡 есть вопрос по использованию микс класса .navigation
вижу, что у тэга nav на всех страницах есть два одинаковых класса class="header__navigation navigation"
как мне кажется, можно все стили положить в .header__navigation и отказаться от использования .navigation
или планируется использовать .navigation в других местах?

2024-09-24 04:58 UTC, kjdhaljkd commented on source/catalog.html
> +      <button class="navigation_button" type="button">
🟢 для интерактивных элементов nav/button можно добавить [aria-label ](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)для увеличения доступности этих элементов.

2024-09-25 10:42 UTC, PolinaGoltsova commented on source/catalog.html
> +    <nav class="header_navigation navigation">
давай обсудим на звонке

2024-09-25 10:46 UTC, PolinaGoltsova commented on source/index.html
> +    <nav class="header_navigation navigation">
в целом получается, что отдельно от хедера навигацию использовать нигде не планируется. Тогда какой класс будет у списка в nav? .header__navigation__list? или .header__navigation header__navigation__list ?

2024-09-26 07:35 UTC, PolinaGoltsova commented on source/index.html
> +    <nav class="header_navigation navigation">
@brewscriptor

2024-09-30 07:44 UTC, PolinaGoltsova commented
@brewscriptor исправила наименования классов, сделала коммит

2024-09-30 08:17 UTC, brewscriptor approved these changes
Отличная работа!

2024-09-30 08:24 UTC, merged