Добавляет svg в меню и футер
PolinaGoltsova/2368577-cat-energy-2 pull request #9
Opened 2024-10-18 06:53 UTC by PolinaGoltsova

Максим, привет! у меня проблема, что на странице не отображаюися иконки, которые я беру из спрайта. Попробовала добавить бургер и крестик-закрытие (из мобилки) в блоке navigation + иконку VK в футере в блоке social.

Когда я начинаю прописывать пусть для background-image, то система не предлагает мне автоматически выбрать папку build и дальше добраться до файла со спрайтами. Я прописываю ее вручную и получается:  background-image: url("../icons/stack.svg#icon-burger"); Пробовала разные варианты.
![Screenshot_1](https://github.com/user-attachments/assets/fc2425fe-1594-4096-b43e-d64fa6999a28)

2024-10-18 11:08 UTC, brewscriptor requested changes

2024-10-18 11:08 UTC, brewscriptor commented on source/styles/blocks/social.scss
> +.social__link--vkontakte {
🔴 тут некоторых свойств не хватает и путь к картинке нужно поправить.
попробуй так:
```
.social__link--vkontakte {
  display: block;
  height: 20px;
  width: 20px;
  background-color: #663399;
  mask-image: url("../../icons/stack.svg#icon-vk");
  mask-position: center;
  mask-repeat: no-repeat;
}
```

2024-10-18 11:08 UTC, brewscriptor commented on source/styles/blocks/navigation.scss
> +  background-color: #000000;
🔴 иконка чёрная и заливка фона чёрная. это делает иконку не видимой под фоном.

2024-10-18 11:08 UTC, brewscriptor commented on source/styles/blocks/navigation.scss
> +  background-image: url("../icons/stack.svg#icon-burger");
🔴 путь к файлу надо поправить, должен быть такой
`../../icons/stack.svg#icon-burger`

2024-10-18 11:08 UTC, brewscriptor commented on source/styles/blocks/navigation.scss
> +  background-image: url("../icons/stack.svg#icon-cross-close");
🔴 `../../icons/stack.svg#icon-cross-close`

2024-10-18 14:24 UTC, PolinaGoltsova commented
@brewscriptor Максим, графику добавила. Посмотри, пожалуйста, все ли верно

2024-10-20 07:49 UTC, brewscriptor requested changes

2024-10-20 07:49 UTC, brewscriptor commented on source/styles/blocks/social.scss
> +  background-color: #666666;
🟢 если цвет встречается больше чем один раз, то можно задуматься о вынесении его в переменные

2024-10-20 07:49 UTC, brewscriptor commented on source/styles/blocks/promo-wrapper.scss
> +  background-color: $brand_green;
🟢 как правило, свойство `background` записывают в одну строку для экономии строк кода, но от этого иногда страдает читабельность.
сейчас править не надо, но ради интереса можно потренироваться записывать его в одну строку.
должно получиться что-то вроде:
`background: $brand_green url("../../images/background-promo-image-mobile@2x.png") no-repeat center / cover;`

2024-10-20 07:49 UTC, brewscriptor commented on source/styles/blocks/benefits.scss
> +.benefits__item--leaf::before {
🔴 повторяющийся код нарушает принцип [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
в селекторах `.benefits__item--leaf::before`, `.benefits__item--powder::before`, `.benefits__item--cutlery::before`, `.benefits__item--watch::before ` меняется только картинка.
рассмотри оптимизировать это так:
```
.benefits__item::before {
  content: "";
  background-repeat: no-repeat;
  width: 60px;
  height: 60px;
  position: absolute;
  left: 0;
  bottom: 0;
}

.benefits__item--leaf::before {
  background-image: url("../../icons/stack.svg#icon-leaf");
}

.benefits__item--powder::before {
  background-image: url("../../icons/stack.svg#icon-powder");
}

.benefits__item--cutlery::before {
  background-image: url("../../icons/stack.svg#icon-cutlery");
}

.benefits__item--watch::before {
  background-image: url("../../icons/stack.svg#icon-watch");
}
```

2024-10-20 07:49 UTC, brewscriptor commented on source/styles/blocks/benefits.scss
> +.benefits__item--leaf::before {
🟡  пройдись по проекту, возможно ещё где-то есть места для оптимизации

2024-10-20 07:50 UTC, brewscriptor commented
> @brewscriptor Максим, графику добавила. Посмотри, пожалуйста, все ли верно

хорошая работа!
есть некоторые правки, пиши если будут вопросы.

2024-10-20 11:59 UTC, brewscriptor approved these changes

2024-10-20 14:04 UTC, merged